apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  namespace: simplebank-prod
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 520894604546.dkr.ecr.us-east-1.amazonaws.com/simplebank:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080