name: CI Tests

on:
  push:
    branches: [master]

jobs:
  test: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: ^1.18.1
        id: go
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Run tests
        run: make test
