name: CI Tests

on:
  push:
    branches: [master]

jobs:
  test: 
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: ^1.18.1
        id: go
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Run migration
        run: make migrateup
      - name: Run tests
        run: make test
