name: Run Unit Tests

on:
  push

jobs:
  test: 
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: ^1.18.1
        id: go
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate
      - name: Run migration
        run: make migrateup
      - name: Run tests
        run: make test
